source 'https://supermarket.chef.io'

cookbook 'apache2'
cookbook 'apt'
cookbook 'chrome'
cookbook 'idea', git:'https://github.com/vptheron/chef-idea.git', ref:'a62b1c4cd93077c87836b005ffade3b379b378a1'
cookbook 'git'
cookbook 'java'
cookbook 'sublime-text', git:'https://github.com/obazoud/sublime-text-cookbook.git', branch:'patch-1'
cookbook 'tig'
cookbook 'vim'
